dist: bionic
language: python
python:
  - "3.6" # current default Python on Travis CI
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt # command to install dependencies
  - pip install . # command to install cuefix
# command to run tests
script:
  - pytest --verbose
